### ISSUE TITLE
can use in cytopathology？

### ISSUE THREAD

**Issue by TingsongYu** [TIO-IKIM/CellViT#1]
Your work is amazing! I was wondering if a method similar to CellViT could be used for detecting pathological cells and classifying WSI levels in digital pathology digital slides (such as cervical cancer cell detection). I would appreciate your suggestions. Thank you!

**Comment by FabianHoerst** [comment]
Vielen Dank für das Kompliment. In general, this repo could help in detecting cervical cancer cells, but additional fine-tuning would be necessary, I gues. Just give it a try. You may also check other solutions like CLAM or this work: 
https://proceedings.mlr.press/v156/butke21a
It depends on your data.
