### ISSUE TITLE
Hello, can you provide a smaller SVS file, such as 5000 * 5000, for testing

### ISSUE THREAD

**Issue by Transformer-man** [TIO-IKIM/CellViT#12]
Hello, can you provide a smaller SVS file, such as 5000 * 5000, for testing

**Comment by Xujingkk** [comment]
Hello, have you tried running it with multiple gpus and have some questions to ask.

**Comment by FabianHoerst** [comment]
Sorry but we cannot provide you with other files. You can inspect TCGA on your own or use files like the CMU WSI testing files.
