### ISSUE TITLE
Training and inference transformations not found

### ISSUE THREAD

**Issue by huangzhii** [TIO-IKIM/CellViT#13]
Hello!

Thanks for deploying this great repo.
I was trying to find training and inference transformations.
However, I haven't been able to locate the details, such as mean and standard deviation. Consequently, this has made it challenging for me to execute the code, including obtaining the necessary `self.run_conf["transformations"]` data.

Could you please provide the detail of your training and inference transformations?

**Comment by FabianHoerst** [comment]
Hello,

the transformations are described in the appendix in the paper. There you should find every entry.

**Comment by huangzhii** [comment]
Thank you. It works perfectly. I evaluated manually and this is indeed the best nuclei segmentation algorithm so far.
