### ISSUE TITLE
The official Panuke datset split?

### ISSUE THREAD

**Issue by JackgreyL** [TIO-IKIM/CellViT#17]
Hi,

From the fold_1-fold3.yaml configuration files,  you used two folds for training and one for validation/testing? This data split is not the official data split, which is one for training, one for validation, and one for testing. Did you compare Hover-net and other SOTA methods using this new split?
Ref. https://warwick.ac.uk/fac/cross_fac/tia/data/pannuke

**Comment by FabianHoerst** [comment]
Hi,

thanks for pointing us to the original split source. We are investigating this. If there is a mismatch, we will provide updated results in a new version of the paper, as it is currently just a preprint with preliminary results. The update could take some time. Thanks for your understanding.

**Comment by windygooo** [comment]
Has the issue been solved?

**Comment by FabianHoerst** [comment]
Yes
