### ISSUE TITLE
python ./preprocessing/patch_extraction/main_extraction.py  

### ISSUE THREAD

**Issue by Transformer-man** [TIO-IKIM/CellViT#2]
when I run python ./preprocessing/patch_extraction/main_extraction.py  ,having error.

![image](https://github.com/TIO-IKIM/CellViT/assets/56433789/4bd51e07-011b-4f9a-84a9-77b257543676)

**Comment by FabianHoerst** [comment]
Could you provide me with more information? What command did you used? What was your cli command? Did you pass over a config file or directly passed over arguments via the cli? It seems like all the fields in the pydantic cli configuration are missing, which should not happen. I am going to investigate it

**Comment by FabianHoerst** [comment]
I also tested the cli for the example file with: 
```bash
python3 ./preprocessing/patch_extraction/main_extraction.py \
    --wsi_paths ./example/TCGA-V5-A7RE-11A-01-TS1.57401526-EF9E-49AC-8FF6-B4F9652311CE.svs \
    --output_path ./example/output/preprocessing \
    --patch_size 1024 \
    --patch_overlap 6.25 \
    --target_mag 40 \
    --processes 6 \
    --patches_per_batch 4 \
    --overwrite \
    --min_intersection_ratio 0.05
```

Which is working well for me

**Comment by FabianHoerst** [comment]
Eine andere Idee: Versuchst du den Code selber zu debuggen? Dann würde ich dir empfehlen, dies über eine eigene debug Datei zu machen, um die Parameter über die CLI zu übergeben. Es muss dann die `launch.json`-Datei im `.vscode` Ordner angepasst werden, und der Debugger für diese datei gestartet werden (see: https://code.visualstudio.com/docs/editor/debugging#_launch-versus-attach-configurations).  The `launch.json` file for the example file could look like this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Preprocessing",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false,
            "subProcess": true,
            "args": [
                "--wsi_paths", "./example/TCGA-V5-A7RE-11A-01-TS1.57401526-EF9E-49AC-8FF6-B4F9652311CE.svs",
                "--output_path", "./example/output/preprocessing",
                "--patch_size", "1024",
                "--patch_overlap", "6.25",
                "--target_mag", "40",
                "--processes", "6",
                "--patches_per_batch", "4",
                "--overwrite",
                "--min_intersection_ratio", "0.05"
            ]
        }
    ]
}
```

You can start debugging then via:
<img width="572" alt="debug-run" src="https://github.com/TIO-IKIM/CellViT/assets/67600643/99a35bbd-461b-40b5-87c4-5930a4e68fa4">

Debugging this gives me the following output:
```shell
2023-07-05 06:01:16,516 [INFO] - Data store directory: /homes/fhoerst/histo-projects/CellViT/example/output/preprocessing
2023-07-05 06:01:16,518 [INFO] - Images found: 1
2023-07-05 06:01:16,521 [INFO] - Annotations found: 0
2023-07-05 06:01:20,935 [INFO] - Removing complete dataset! This may take a while.
2023-07-05 06:01:21,841 [INFO] - Using 6 processes.
2023-07-05 06:01:21,906 [INFO] - **************************************************************************************************************************************
2023-07-05 06:01:21,908 [INFO] - 1/1: TCGA-V5-A7RE-11A-01-TS1.57401526-EF9E-49AC-8FF6-B4F9652311CE.svs
2023-07-05 06:01:21,910 [INFO] - Computing patches for TCGA-V5-A7RE-11A-01-TS1.57401526-EF9E-49AC-8FF6-B4F9652311CE.svs
2023-07-05 06:02:21,552 [INFO] - TCGA-V5-A7RE-11A-01-TS1.57401526-EF9E-49AC-8FF6-B4F9652311CE.svs: Processing 58 patches.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:15<00:00,  1.04s/it]
2023-07-05 06:02:42,571 [INFO] - Total patches sampled: 58
2023-07-05 06:02:43,437 [INFO] - Patches saved to: /homes/fhoerst/histo-projects/CellViT/example/output/preprocessing
2023-07-05 06:02:43,438 [INFO] - Total patches sampled for all WSI: 58
2023-07-05 06:02:43,450 [INFO] - Time usage: 0:01:21.543524
```

**Comment by Transformer-man** [comment]
Thank you very much for your help. I will try again following your steps

**Comment by Transformer-man** [comment]
It seems like the same mistake
![image](https://github.com/TIO-IKIM/CellViT/assets/56433789/8cefc35d-a9c8-496d-8b9f-1351f7e00eca)

**Comment by Transformer-man** [comment]
When I run python3 ./preprocessing/patch_extraction/main_extraction.py --config ./example/preprocessing_example.yaml，having the same mistake.
![image](https://github.com/TIO-IKIM/CellViT/assets/56433789/6cb86af4-2100-4f2b-b155-22aa2322b5ba)

**Comment by FabianHoerst** [comment]
Have you checked the debugging launch.json I provided? Could you please set a breakpoint in line 534 in file `preprocessing/patch_extraction/src/cli.py` and check the output of the `opt_dict`?

**Comment by Transformer-man** [comment]
Copy that, I'll do it right away

**Comment by Transformer-man** [comment]
![image](https://github.com/TIO-IKIM/CellViT/assets/56433789/b79e8d37-e137-4c09-b241-fa3b094b1ca8)

**Comment by FabianHoerst** [comment]
Maybe we should take this discussion offline. Contact me at fabian.hoerst@uk-essen.de

**Comment by Transformer-man** [comment]
![image](https://github.com/TIO-IKIM/CellViT/assets/56433789/978ab63e-416a-466e-a280-e86aa7093610)

**Comment by Transformer-man** [comment]
An error was reported when running to this line

**Comment by Transformer-man** [comment]
Okay, I'll contact you right away

**Comment by FabianHoerst** [comment]
Very strange behavior. My yaml_config dict looks exactly the same as yours:
```
{'wsi_paths': './example/TCGA-V5-A7...2311CE.svs', 'output_path': './example/output/preprocessing', 'patch_size': 1024, 'patch_overlap': 6.25, 'target_mag': 40, 'processes': 6, 'patches_per_batch': 4, 'overwrite': True, 'normalize_stains': True, 'min_intersection_ratio': 0.05}
```
Executing `PreProcessingYamlConfig(**yaml_config)` should return a PreProcessingYamlConfig PyDantic object with all other values initialized by None or a default value.

**Comment by Transformer-man** [comment]
Yes, I haven't made any changes, except for using my own data. Everything else is based on your side. But PreProcessingYamlConfig(**yaml_config) has error.

**Comment by Transformer-man** [comment]
I've found the reason, I'm really stupid. I originally used Pydantic version 2.0, but yours is version 1.10.4, which is due to the version.
![image](https://github.com/TIO-IKIM/CellViT/assets/56433789/8d52a738-5ea5-4e9a-a81b-d4f75c128b5f)

**Comment by Transformer-man** [comment]
Thank you very much for your help. I have wasted so much of your time.

**Comment by FabianHoerst** [comment]
Ok, good to know the version mismatch. Thanks for resolving this and a note to myself for next projects with new paydantic api! In general, please use provided environments. 
I am also currently implementing a speedup for inference, should be merged next week, as the code was not optimized right now. I expect to have a 10x speed up for inference with `cell_detection.py`.

**Comment by Transformer-man** [comment]
Very good work, thanks for your help
