### ISSUE TITLE
Inference speed improved by x100 for postprocessing,But there are still serious time-consuming

### ISSUE THREAD

**Issue by 464hee** [TIO-IKIM/CellViT#20]
**Describe the bug**
Despite the speedup, I tested and found that the post-processing time was 3 times the predicted time for this

**To Reproduce**
1. Command
2. File
3. Error Traceback
[reproduce.zip](https://github.com/TIO-IKIM/CellViT/files/12615154/reproduce.zip)
This is my test code for my video
The test found that all other conditions are the same, only change whether to use post-processing operation, without post-processing, the time consumed 6s, the use of post-processing time consumed 21.9, the test results lead to a conclusion, if the post-processing can be further speed up, or put in the GPU processing, may also be able to speed up the prediction process a lot!

**Expected behavior**
I want the post-processing time to be less than the prediction time
**Screenshots**

**Additional context**
@FabianHoerst

**Comment by FabianHoerst** [comment]
We will investigate this matter further. While we acknowledge the upfront costs, it's worth noting that postprocessing time becomes negligible when conducting inference on large WSIs with numerous 1024px tiles.

**Comment by 464hee** [comment]
![image](https://github.com/TIO-IKIM/CellViT/assets/100740023/02e33d11-3444-4c30-8087-cb697095e0fe)
The time-consuming operation comes from the code under the get_cell_predictions_with_tokens function: ( _,instance_types,) = self.model.calculate_instance_map(predictions, magnification= magnification), which is what every 1024*1024 plot prediction must go through

**Comment by 464hee** [comment]
So I think the time consumption is still noteworthy on many large 1024*1024 wsi images

**Comment by FabianHoerst** [comment]
Ok, I thought you mean the cell merging. We are going to investigate this, but for this a major rewrite of the HoVerNet postprocessing is necessary.

**Comment by 464hee** [comment]
OK, if this function is accelerated, I believe that the prediction of the whole big picture will achieve even better prediction speeds.
