### ISSUE TITLE
Train a data set with only one tissue type

### ISSUE THREAD

**Issue by Transformer-man** [TIO-IKIM/CellViT#21]
Hello, my data set has only one tissue type. How do I modify the training configuration? Or do you provide training configuration here? Do we need to close the issue type branch directly, or do we need to manually modify the network?

**Comment by FabianHoerst** [comment]
If you just have on tissue type, just delete the tissue-branch or provide always the same label in your dataset

**Comment by FabianHoerst** [comment]
It is possible from machine learning theory. You could also remove the entire tissue_types loss part in the config, but in both cases, the scripts will fail. You need to remove everything associated with the tissue_type calculation, e.g., the tissue-related metrics. But it should be really straightforward. Write your own data loader and fix every error that occurs related to tissue types (e.g., missing dictionary entries in prediction and ground truth).
