### ISSUE TITLE
Binary weight factors?

### ISSUE THREAD

**Issue by GlastonburyC** [TIO-IKIM/CellViT#22]
How are these hardcoded binary weight factors computed for the nukeseg data?
https://github.com/TIO-IKIM/CellViT/blob/60a03edc87e26fcc0ba8e6f184e449ca6b580e74/cell_segmentation/datasets/pannuke.py#L225

**Comment by FabianHoerst** [comment]
Hello, we explain the weights computing in section 4.4.
