### ISSUE TITLE
How about the segmentation performance on other benchmarks like CoNSeP,  CPM-17?

### ISSUE THREAD

**Issue by windygooo** [TIO-IKIM/CellViT#24]

**Comment by windygooo** [comment]
And would the pretrained weights on each PanNuke fold be released?

**Comment by FabianHoerst** [comment]
Hello, thanks for your inquiry!

We have not trained the networks on other datasets, but validated the results on Monuseg and CoNSeP. In our opinion, there is no other dataset that is comparable to PanNuke. See the Table attached, which is from the Paper: [Lizard: A Large-Scale Dataset for Colonic Nuclear Instance Segmentation and Classification](https://openaccess.thecvf.com/content/ICCV2021W/CDPath/papers/Graham_Lizard_A_Large-Scale_Dataset_for_Colonic_Nuclear_Instance_Segmentation_and_ICCVW_2021_paper.pdf). 

<img width="331" alt="Bildschirm­foto 2023-10-09 um 08 02 02" src="https://github.com/TIO-IKIM/CellViT/assets/67600643/dcb21620-1936-4e8f-83db-ec5d0362630d">

Training on Lizard would be possible, but the test dataset is not publicly available and the dataset is just from one tissue type. We therefore decided to use the other datasets (Monuseg, CoNSeP) to validate our PanNuke trained networks. Sharing all pretrained network weights is not possible, as each checkpoint encompasses multiple GB and the whole result directory with each checkpoint for all three folds needs more than 1TB of storage. However, you can retrain the networks with our provided training scripts by yourself if this is necessary.

**Comment by windygooo** [comment]
Thanks for your reply!
Will the training config files for the PanNuke dataset be released?

**Comment by windygooo** [comment]
> Thanks for your reply! Will the training config files for the PanNuke dataset be released?

I have seen it.
