### ISSUE TITLE
Docker Image progress

### ISSUE THREAD

**Issue by tomvars** [TIO-IKIM/CellViT#29]
Have been unsuccessful following the installation instructions, I hit

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - cucim -> __glibc[version='>=2.17,<3.0.a0']
  - cucim -> cupy[version='>=9,<12.0.0a0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
```

When running `conda install -c rapidsai cucim` (Ubuntu 20.04.1, CUDA 12.0)

Feel a docker image would be a big step forward. Starting from the rapidsai/base image seems to work relatively well but then the issue is installing OpenSlide from source. Any update on the docker image would be appreciated 🙏

**Comment by FabianHoerst** [comment]
Is the error just related to cucim? Could you provide me with more details about the error (When does it fail, steps to reproducte etc.). Is installing openslide from anaconda an option for the docker container as it should install all binaries?

**Comment by kaczmarj** [comment]
>Is installing openslide from anaconda an option for the docker container as it should install all binaries

it would be. another option would be to install the openslide system package. on debian-derivatives, this would be

```
apt-get install libopenslide0
```
