### ISSUE TITLE
When I use 3090 for prediction, it shows memory overflow。Model is CellViT-256.

### ISSUE THREAD

**Issue by Transformer-man** [TIO-IKIM/CellViT#3]
![image](https://github.com/TIO-IKIM/CellViT/assets/56433789/b7dcd43a-fc01-4bd4-84d6-82b77dadae91)

**Comment by Transformer-man** [comment]
How can I use a smaller memory

**Comment by FabianHoerst** [comment]
During training or Inference? The Code is optimized to run on a 48GB Nvidia Device. During Training, reduce the batch size. For inference, you need to reduce the inference batch size in `cell_detection.py`. However, we are currently improving the inference performance and will also add a batch-size parameter for smaller GPUs 

``` Python
wsi_inference_dataloader = DataLoader(
    dataset=wsi_inference_dataset,
    batch_size=8,
    num_workers=16,
    shuffle=False,
    collate_fn=wsi_inference_dataset.collate_batch,
    pin_memory=False,
)
```

**Comment by FabianHoerst** [comment]
Batch-size parameter has been added. Please check the new inference parameters in the cli. Using a size of 2 or 4 should work with your code
