### ISSUE TITLE
How to calculate the STD metrics shown in Table 3 of your paper? 

### ISSUE THREAD

**Issue by windygoo** [TIO-IKIM/CellViT#31]

**Comment by FabianHoerst** [comment]
Average over the 3 folds, take the standard deviation with the `np.std`

**Comment by windygoo** [comment]
first calculate the std for each tissue across three folds and compute the average across all tissues 
Or
first calculate the std for all tissues in each fold and compute the average std across three folds.

**Comment by FabianHoerst** [comment]
Please be more precise in your question next time from the beginning and do not just add a title. I do not want to guess your problems.. Average the folds to get tissue results, then average this.

**Comment by windygoo** [comment]
> Please be more precise in your question next time from the beginning and do not just add a title. I do not want to guess your problems.. Average the folds to get tissue results, then average this.

Get it! Thanks!
