### ISSUE TITLE
When performing inference on the MoNuSeg dataset, the following code will ignore some regions of a image. 

### ISSUE THREAD

**Issue by windygoo** [TIO-IKIM/CellViT#35]
Given an image of size (3, 1000, 1000), the shape of returned tensor is (3, 4, 4, 256, 256). Actually, if using overlap of 64 pixels, the shape should be ((3, 5, 5, 256, 256)).

![image](https://github.com/TIO-IKIM/CellViT/assets/109289312/0fde0684-cd90-420f-b6c7-07ef77b02e42)

Illustration:

Input: 
a = torch.arange(1000)
b = a.unfold(0, 256, 256 - 64)
print(b)

Output:
tensor([[  0,   1,   2,  ..., 253, 254, 255],
        [192, 193, 194,  ..., 445, 446, 447],
        [384, 385, 386,  ..., 637, 638, 639],
        [576, 577, 578,  ..., 829, 830, 831]])

The rest region from 832 to 999 is ignored during inference.

**Comment by FabianHoerst** [comment]
You should rescale the input images and ground-truth masks to 1024x1024 pixels to make them divisible by the token size.

**Comment by windygoo** [comment]
> You should rescale the input images and ground-truth masks to 1024x1024 pixels to make them divisible by the token size.

Ok, thanks!
