### ISSUE TITLE
Can't reproduce the results of your paper

### ISSUE THREAD

**Issue by ziwei-cui** [TIO-IKIM/CellViT#36]
I attempted to reproduce the results of your paper using an NVIDIA RTX 3090, and I followed the configs exactly as described in your paper. The paper reported results of 0.6464 and 0.5 for bPQ and mPQ, respectively, on the PanNuke dataset using the CellViT256 model. However, when I reproduced the experiment, I obtained results of 0.6157 for bPQ and 0.4805 for mPQ. I'm wondering what factors you think might have influenced this discrepancy？

**Comment by FabianHoerst** [comment]
Could you be more specific about the configuration?

For the CellViT256 Model, we reported the following results: `0.4846 mPQ, 0.6696 bPQ`. Have you used the provided config files? Have you used the right split (provided here: https://warwick.ac.uk/fac/cross_fac/tia/data/pannuke)? 

One reason could be non-deterministic training behaviour and seeding of each worker. We tried to get the code as much reproducible as possible. However, some implementations are non-deterministic and therefore `TORCH.USE_DETERMINISTIC_ALGORITHMS`could not be applied.

For transparency, we published all training logs and and config files. You can find the respective training logs here: 
[logs_paper/PanNuke/CellViTHV/ViT256/Best-Setting/Fold-1/inference_results.json](logs_paper/PanNuke/CellViTHV/ViT256/Best-Setting/Fold-1/inference_results.json)

**Comment by ziwei-cui** [comment]
[logs.log](https://github.com/TIO-IKIM/CellViT/files/13713405/logs.log)
This is my training log

> 您能更具体地介绍一下配置吗？
> 
> 对于 CellViT256 模型，我们报告了以下结果：`0.4846 mPQ, 0.6696 bPQ`。您使用过提供的配置文件吗？您是否使用了正确的分割方式（此处提供：https://warwick.ac.uk/fac/cross_fac/tia/data/pannuke）？< /span>
> 
> 原因之一可能是每个工作人员的不确定性培训行为和播种。我们试图让代码尽可能具有可重复性。但是，某些实现是不确定的，因此`TORCH.USE_DETERMINISTIC_ALGORITHMS`无法应用。
> 
> 为了透明起见，我们发布了所有训练日志和配置文件。您可以在此处找到相应的训练日志： [logs_paper/PanNuke/CellViTHV/ViT256/Best-Setting/Fold-1/inference_results.json](logs_paper/PanNuke/CellViTHV/ViT256/Best-Setting/Fold-1/inference_results.json)

[logs.log](https://github.com/TIO-IKIM/CellViT/files/13713416/logs.log)
I have checked my configuration based on your suggestions, and I trained the model following your configuration file exactly. This is my training log, and it looks very similar to yours. However, what troubles me is that I could only find this table2 regarding the description of '0.4846 mPQ, 0.6696 bPQ' in your paper.
![屏幕截图 2023-12-19 171613](https://github.com/TIO-IKIM/CellViT/assets/117881100/eea7adf7-1f51-4c58-9ca5-b4150ce87e44)

**Comment by FabianHoerst** [comment]
We published a resvised version, as we had some minor inconsistencies regarding the official splitting and metrics in the first version. Please take a look here: https://arxiv.org/abs/2306.15350

<img width="725" alt="Bildschirm­foto 2023-12-19 um 10 42 37" src="https://github.com/TIO-IKIM/CellViT/assets/67600643/9d822608-91d6-4d3d-affe-78ea4e72df71">

To get the results from the paper, you need to run the inference on the test dataset, then average them for each fold.

**Comment by ziwei-cui** [comment]
OK.I got it!Thanks!

**Comment by ziwei-cui** [comment]
> 我们发布了修订版，因为我们在第一个版本中的官方划分和指标方面存在一些细微的不一致。请看这里：https://arxiv.org/abs/2306.15350
> 
> <img alt="图片摄影 2023-12-19 um 10 42 37" width="725" src="https://private-user-images.githubusercontent.com/67600643/291544804-9d822608-91d6-4d3d-affe-78ea4e72df71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODQ1MjksIm5iZiI6MTcwMjk4NDIyOSwicGF0aCI6Ii82NzYwMDY0My8yOTE1NDQ4MDQtOWQ4MjI2MDgtOTFkNi00ZDNkLWFmZmUtNzhlYTRlNzJkZjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDExMTAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYTZlN2I3NTlkMmUyOTQxYTdmMzgzYmVhZjk0ZWUxNDM0MzNjNWM3NGM1MTk4ZTZjNTJjZWRjYzE3NzAzZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JHh9nMaagpd__ejusfY4sEkIJa6QYlFJCQ8_3e4EiQw">
> 要从论文中获得结果，您需要在测试数据集上运行推理，然后对每次折叠进行平均。

OK.I got it!Thanks!

**Comment by yazeedalrubyli** [comment]
Can you help me with the paper results?

In your best setting in the repo [logs_paper/PanNuke/CellViTHV/ViT256/Best-Setting] [bPQ] are the following:
Fold1: 0.6508239484962763
Fold2: 0.650604077220339
Fold3: 0.6595421655228957
---------
avg: 0.65365673041

How come you got avg is 0.6696 in the paper?

Thank you in advance.

**Comment by FabianHoerst** [comment]
@yazeedalrubyli please see the comment under your issue, the bPQ values you refer to are derived from a different averaging strategy and with another calculation scheme within our validation loop.

**Comment by yazeedalrubyli** [comment]
@FabianHoerst Thank you very much.

**Comment by yazeedalrubyli** [comment]
In the abstract, it is mentioned that the mean PQ is 0.5. How did you come with that?

Thank you.

**Comment by FabianHoerst** [comment]
Rounding 0.498 to 2-Decimal precision Results in 0.50 😄

**Comment by yazeedalrubyli** [comment]
@FabianHoerst  Thank you very much.
