### ISSUE TITLE
Application to non-contiguous patches

### ISSUE THREAD

**Issue by florianbuettner** [TIO-IKIM/CellViT#39]
Hi, very interesting work and thanks for sharing the code! 
I would like to test CellVit on a set of non-contiguous patches (1024x1024, 0.25 Micrometer) from different WSI. Should I start with cell_segmentation/inference/inference_cellvit_experiment_pannuke.py and adapt it if necessary? Is it advisable to perform a stain normalization beforehand?
Thanks!

**Comment by FabianHoerst** [comment]
Hello,

exactly, you could use this or the MoNuSeg Inference Code. I have not compared the performance with and without stain normalization, but from Intuition, I would use it.
