### ISSUE TITLE
sweep init failed for training

### ISSUE THREAD

**Issue by randy-tsukemen** [TIO-IKIM/CellViT#4]
Thank you for sharing great work!

While I tried to reproduce the training part, the [`train_cellvit.yaml`](https://github.com/TIO-IKIM/CellViT/blob/main/configs/examples/cell_segmentation/train_cellvit.yaml) is hard for me to understand the format.
Do I need to fill them with the sweep format with `max` and `min` like below?
```
'parameters': 
    {
        'x': {'max': 0.1, 'min': 0.01},
        'y': {'values': [1, 3, 7]},
     }
```

I also tried to figure out how to use the [`insert_parameter_tag`](https://github.com/TIO-IKIM/CellViT/blob/main/utils/tools.py#L195) function since it looks like we need to parameters tag to push to wandb but currently the function is not used in the code.

If possible, could you kindly provide the filled `train_cellvit.yaml`?

**Comment by FabianHoerst** [comment]
I removed the function `insert_paramezer_tag`, as it was not used. Tags have to be given inside the .yaml configuration file. I added a new configuration file [`train_cellvit_sweep.yaml`](/configs/examples/cell_segmentation/train_cellvit_sweep.yaml) for wandb sweeps, hopefully explaining the use of sweeping parameters. Unfortunately, we cannot share all configuration files as the work is still under peer review.
