### ISSUE TITLE
MuNoSeg data set execution code

### ISSUE THREAD

**Issue by CYYJL** [TIO-IKIM/CellViT#41]
HI, I am very interested in your work, and I want to quote your paper, but I have encountered a problem of data set training, may I ask if there is a training code of MuNoseg data set? I only found the training code of CoNic data, and the training codes of CoNic, MuNoSeg and Pannuke are different.

**Comment by FabianHoerst** [comment]
Hi there,

Thank you for reaching out. Since we've only conducted inference on the MoNuSeg dataset without any training, we don't have any training code available. However, if you need assistance or have specific questions, I'm more than happy to help. Please provide more details about your problem and what you're trying to achieve, and I'll do my best to assist you further.

**Comment by CYYJL** [comment]
> Hi there,
> 
> Thank you for reaching out. Since we've only conducted inference on the MoNuSeg dataset without any training, we don't have any training code available. However, if you need assistance or have specific questions, I'm more than happy to help. Please provide more details about your problem and what you're trying to achieve, and I'll do my best to assist you further.

Thanks, may I ask is the reasoning directly using the training weights in pannuke? I feel a little confused in this place. Also, I think the code your write is great, thanks you so much

**Comment by FabianHoerst** [comment]
Exactly. We use the models trained on PanNuke there

**Comment by CYYJL** [comment]
> Exactly. We use the models trained on PanNuke there

I got it, thank you very much. Can you ask if there is any google drive or onedrive download of CoNic dataset?  We cannot download this data set from the website you provide

**Comment by FabianHoerst** [comment]
Sure. As we did not include any experiments on the conic dataset in the paper as the scope was different and we pursue a different research direction, we have not included the links. We just provided the code as it might be useful for someone who wants to try it. You can find the data here: https://conic-challenge.grand-challenge.org/

If you do not have any more questions, I would close the issue now 👍🏼
