### ISSUE TITLE
cell_detection_mp looking for files that don't exist

### ISSUE THREAD

**Issue by bendmartin** [TIO-IKIM/CellViT#45]
**Describe the bug**

Running cellvit/cell_segmentation/inference/cell_detection.py works perfectly for me. However, cell_detection_mp.py is not consistent with cell_detection.py or cell_detection_256.py

Firstly, the imports are not relative like the other files -- lines 36, 67, 71, 72, 80-83 all import "from cellvit.x.x" rather than simply "x.x" as in cell_detection.py.

Secondly, some files and functions are missing:
Line 36: from cellvit.cell_segmentation.utils.post_proc import DetectionCellPostProcessor
- There is no file in cell_segmentation/utils named post_proc, instead post_proc_cellvit
Line 66: from zcell_segmentation.datasets.cell_graph_datamodel import CellGraphDataWSI
- There is no zcell_segmentation directory
Lines 75, 77, 78: CellViT256Unshared, CellViTSAMUnshared, CellViTUnshared
- By the name, I'm assuming these are development versions which are hidden from the user and thus cannot be imported

I'm unsure if this is an oversight or if cell_detection_mp is simply not meant to be used. Comparing the code, it looks like it has some useful features, so it would be cool if a usage guide was available and/or these issues were fixed. 

**To Reproduce**

python cell_segmentation/inference/cell_detection_mp.py -h

**Comment by FabianHoerst** [comment]
Hi, the provided file is not meant to be used right now. We are currently working on a new version of this repository, which will be published in the next months, with increased inference speed and more features. 

I will remove the corresponding file, we mixed something between our development and public repository.

Thanks for reporting!
