### ISSUE TITLE
Issue with downsampling

### ISSUE THREAD

**Issue by pkeller00** [TIO-IKIM/CellViT#47]
**Describe the bug**
Preprocessing code fails for images with an odd number of levels.
**To Reproduce**
1. Select image from TCGA with odd number of levels e.g. TCGA-AA-3673-01Z-00-DX1.a80676fa-5481-4b63-9639-dbeb31ae82d8.svs (17 levels)
2. Run `python3 ./preprocessing/patch_extraction/main_extraction.py --config ./example/preprocessing_example.yaml `with the default processing file provided in GitHub. (Default downsample of 1)
3. "Requested level does not exist. Number of slide levels: 17"

**Expected behavior**
This occurs as `level = tiles.level_count - self.config.downsample.bit_length()` set level to 17 rather than 16 which is not correct.

**Comment by pkeller00** [comment]
After further investigation it seems the issue is because the slide does not have power information. Adding a value for target_mpp solved the issue.

**Comment by FabianHoerst** [comment]
I am going to investigate this, as it is more or less a preprocessing problem. Either way, the preprocessing should terminate with an error message when the target_mpp cannot be loaded and needs to be specific explicitly.

**Comment by FabianHoerst** [comment]
It seems like the slide has a kind of "odd" setting. It is scanned with a magnification of x20, but has 0.2325 mpp as resolution. We are going to improve the code soon. Thanks for reporting!
