### ISSUE TITLE
Comparison to PLUTO paper?

### ISSUE THREAD

**Issue by cgebbe** [TIO-IKIM/CellViT#48]
Thank you for your great paper and code first of all!

The recent PLUTO paper (https://arxiv.org/pdf/2405.07905) also benchmarked its work. It uses the following decoders:

- Mask2Former (from 06/2022, see https://arxiv.org/pdf/2205.08534)
- Mask-RCNN with Vit adaption head (from 02/2023, see https://arxiv.org/pdf/2205.08534)
- HoverNet (like you)

Questions:

1. Since your paper was published 10/2023, have you also tried out by chance Mask2Former or the ViT adaption head? 
2. In my naive understanding, PLUTO + Hovernet is likely very similar to CellVit + Hovernet or am I missing important details?

**Comment by FabianHoerst** [comment]
Hi,

thank you for the great question. Regarding 1: We have not tested the Mask2Former approach. However, I am also curious on how it would perform, but do not have the capacity right now to test it. 
Regarding 2: I am not sure if you can state this totally, as the ViT encoder used by Pluto is a FlexiViT network, like explained here [https://arxiv.org/pdf/2212.08013](https://arxiv.org/pdf/2212.08013). I am also not sure about the multiscale input images. I would say, that there model is a more general one, encompassing a broader range of tasks that can be solved with it.
