### ISSUE TITLE
Error report for cellvit_cpp_net.py

### ISSUE THREAD

**Issue by won5830** [TIO-IKIM/CellViT#49]
For line 358 ~363
`dist_map_features = self._forward_upsample( z0, z1, z2, z3, z4, self.dist_decoder)  
type_map_features = self._forward_upsample( z0, z1, z2, z3, z4, self.dist_decoder)
`
dist_map_features & type_map_features both upsamples from self.dist_decoder. 
Shouldn't the latter one be self.nuclei_type_maps_decoder ?

**Comment by FabianHoerst** [comment]
Thanks for the issue, we are testing it in the following days.

**Comment by FabianHoerst** [comment]
Fixed!
