### ISSUE TITLE
three-fold cross-validation

### ISSUE THREAD

**Issue by CYYJL** [TIO-IKIM/CellViT#51]
Hi, Could you please explain how to perform three-fold cross-validation in your code? Isn't it about alternately using three datasets for training, testing, and validation?

**Comment by FabianHoerst** [comment]
Hi,

for three folds, you would need the respective config files, one your each fold. In the config files, you define the train and validation folds. The test fold is not regarded in the config file, rather there are specific evaluation scripts in which the test fold is then used.
