### ISSUE TITLE
ROI Support

### ISSUE THREAD

**Issue by KompressorSC** [TIO-IKIM/CellViT#52]
Hi,

I really appreciate your work. Recently I am trying to use CellViT to run inference on ROIs, but I don't know how to modify the pipeline. May you give some advices?

**Comment by FabianHoerst** [comment]
Hi, can you be more specific and explain what you mean with ROI? Do you have an anonymized example file you could share with me?

**Comment by KompressorSC** [comment]
Hi, I want to use CellViT to segment ROI, but I find  the model can only segment WSI. How can I modify it to segment ROI? I’ll provide some anonymized example files later.

---- Replied Message ----
| From | Fabian ***@***.***> |
| Date | 08/08/2024 22:12 |
| To | TIO-IKIM/CellViT ***@***.***> |
| Cc | Sicheng ***@***.***>,
Author ***@***.***> |
| Subject | Re: [TIO-IKIM/CellViT] ROI Support (Issue #52) |

Hi, can you be more specific and explain what you mean with ROI? Do you have an anonymized example file you could share with me?

**Comment by KompressorSC** [comment]
Hi, I worked it out by myself. I will close this issue. Thanks.
