### ISSUE TITLE
Do you find the training unstable for ViT-S based encoders?

### ISSUE THREAD

**Issue by swarajnanda2021** [TIO-IKIM/CellViT#53]
I've experienced nan issues with ViT-S encoders, but when I change the DeConv2d params from:

            self.bottleneck_dim = 312
            
to:

            self.bottleneck_dim = 256
            

This issue is somewhat ameliorated. 

Could there be an issue with dimensioning the decoder blocks for embedding dimensions less than 512?

**Comment by FabianHoerst** [comment]
Hello, I did not experience instabilities during training for the ViT-S encoders. However, as I am not able to reproduce, the error might arise from mixed-precision training, wrong input scale, differing package versions etc.

I am very sorry that I cannot help you. If switching the dimension works for you and the training is more stable, I would recommend then to use your version.

**Comment by swarajnanda2021** [comment]
Hello, switching to full precision stabilized the training.
