### ISSUE TITLE
Cell type label

### ISSUE THREAD

**Issue by JiawenChenn** [TIO-IKIM/CellViT#54]
Hi, I am trying to use CellViT for cell segmentation using the CellViT-256-x20.pth model. Could you clarify how to find the corresponding cell types using cells.json? Or what's the right file to use? What's **type** and **cell_status** column in cells.json? Thanks a lot!!

**Comment by FabianHoerst** [comment]
Do you mean the interpretation of those labels?
If I understood you correctly, it is the following:
```python
nuclei_types:
  Background: 0
  Neoplastic: 1
  Inflammatory: 2
  Connective: 3
  Dead: 4
  Epithelial: 5
```

I'll add this to the readme. Thanks a lot for the hint!
