### ISSUE TITLE
Dockerfile may be of use

### ISSUE THREAD

**Issue by PingjunChen** [TIO-IKIM/CellViT#57]
**Describe the bug**
I prepared a Dockerfile (attached), which can configure a running environment that runs CellViT functionalities just fine so far on my end. Thinking Dockefile might be useful for your preparation of a Docker Image for CellViT.

[Dockerfile.txt](https://github.com/user-attachments/files/16630052/Dockerfile.txt)

**Comment by FabianHoerst** [comment]
Truly, many many thanks! I currently don't have the resources to advance such developments, which is why I am really grateful for this support! I will add this later and give you credits!
