### ISSUE TITLE
Generate cell contours for the three folds of the Pannuke dataset

### ISSUE THREAD

**Issue by CCSSMP** [TIO-IKIM/CellViT#58]
Hi, could you please tell me if ./cell_segmentation/inference/cell_detection.py can generate and save cell contours for the three fold files in the Pannuke dataset? If so, how should the initialization parameters be set?
![1724468089056](https://github.com/user-attachments/assets/592d2a11-610e-4b12-a2a9-8f373136d926)

**Comment by FabianHoerst** [comment]
No, it is not intended to do so. We used a callback inside the training script to do so. Should be not that hard to do it on your own, but we do not want to change the code at this stage for edge cases. Just make a jupter notebook, load the model checkpoint within pytorch, perform segmentation like in the inference scripts and overlay them over the images with PIL.ImageDraw (draw contours method).

Best, Fabian
