### ISSUE TITLE
UMAP of CellViT

### ISSUE THREAD

**Issue by Liruieat** [TIO-IKIM/CellViT#62]
Hello,

I've been trying to implement UMAP in the context of CellViT, but my results have been quite messy. It seems that the cells from different classes are mixed together rather than showing clear clustering patterns. I was wondering if you could briefly explain some of the implementation details and, if possible, share the UMAP implementation code.

Specifically, I'd like to understand the following:

1、Does the embedding representing each nucleus correspond to an individual nucleus, or is it a small patch containing additional background information?
2、If the embedding comes from an RGB patch with multiple nuclei, which nucleus does the embedding represent?
3、I noticed that the final UMAP visualization shows distinct clusters. Was there any additional processing applied to the features obtained from UMAP, such as further clustering?

Thank you very much for your time and assistance!

**Comment by FabianHoerst** [comment]
Here is the translation:

---

Hello,

Sorry for my late response, unfortunately I missed your message. For the creation of the UMAP features, the resulting .pt files are used. For the color overlay, we use the GT annotations of the data. From that, we perform UMAP. The features are then transformed by UMAP into a 2D representation and displayed with the ground-truth color overlay.

To your questions:
1. Each embedding is mapped to one nucleus, but a token has the size of 16x16 pixels, so there might be background. If multiple tokens belong to one nucleus, they have been averaged.
2. We do not use the class token, but a 16x16 token grid, mapping back the tokens of the last transformer layer to each nucleus.
3. We did not apply additional processing.

Thank you for your question!
Fabian
