### ISSUE TITLE
prepare_pannuke doesn't make types.csv

### ISSUE THREAD

**Issue by donniekramer8** [TIO-IKIM/CellViT#63]
python3 prepare_pannuke.py --input_path ~/Downloads/pannuke/ --output_path ~/data/pannuke/CellViT_processed

Creates png and npy files as intended, however, when running the following

python3 run_cellvit.py --config ~/pannuke_config.yaml

I get error:

FileNotFoundError: [Errno 2] No such file or directory: ~/CellViT_processed/fold0/types.csv

It seems as though the prepare_pannuke script is intended to process the dataset but it fails to create this csv file

**Comment by FabianHoerst** [comment]
Hi, you can find the types inside this folder of this repo:
https://github.com/TIO-IKIM/CellViT/blob/main/configs/datasets/PanNuke/
