### ISSUE TITLE
Pip failed when using environment.yml

### ISSUE THREAD

**Issue by linatakemaru** [TIO-IKIM/CellViT#64]
Hi, I'm having issues creating a conda environment from the provided environment.yml file. The command I used is `conda env create -f environment.yml.` I believe the issue is encountered during installation of the open slide dependencies. Below are screenshots of the output. 

I appreciate the help! This error is reproducible on multiple machines and users. Thank you!

<img width="982" alt="1" src="https://github.com/user-attachments/assets/856e6d79-1b51-4db8-bf43-0bba55499928">
<img width="979" alt="2" src="https://github.com/user-attachments/assets/71b91603-6c37-4a0f-893f-3cf12322e391"><img width="978" alt="3" src="https://github.com/user-attachments/assets/79c9296f-3f15-40fe-9a84-d92cf3fb6384">

**Comment by linatakemaru** [comment]
Hi, I really appreciate your response! I did see that thread, but I don't have the crypt.h file in my anaconda3/include folder

**Comment by lisafournier** [comment]
Yes but do you have it in /usr/include? If yes then you can copy it where you need in the /include folder of your anaconda env)

**Comment by linatakemaru** [comment]
Fixed using `module load gcc/10.2.0`
