### ISSUE TITLE
Regarding the issue of inferring the pannuke dataset using a pre-trained model.

### ISSUE THREAD

**Issue by xinxiaoxiong** [TIO-IKIM/CellViT#69]
Dear author, 

After processing the pannuke dataset according to your method, when I run the file **CellViT-main/cell_segmentation/inference/inference_cellvit_experiment_pannuke.py**, I find that the config.yaml file is missing. May I ask how the config.yaml file for the pannuke dataset should be written? Or where can I see a template?

I am looking forward to your reply very much. Wish everything goes smoothly.

**Comment by FabianHoerst** [comment]
Hi,

please check out the log folder. 

Best, Fabian
