### ISSUE TITLE
Data preprocessing error

### ISSUE THREAD

**Issue by niuhulu-rui** [TIO-IKIM/CellViT#71]
这是我的配置文件：
# dataset paths
wsi_paths: /data2/longdan/datasets/naomo/kfb12023-11-21_07_00_45.svs
output_path: ./example/output/preprocessing

# basic setups
patch_size: 1024
patch_overlap: 6.25
target_mag: 40
processes: 8
overwrite: True

# macenko stain normalization
normalize_stains: True

# finding patches
min_intersection_ratio: 0.05
运行命令行：
python3 ./preprocessing/patch_extraction/main_extraction.py --config ./example/preprocessing_example.yaml
运行结果：
Traceback (most recent call last):
  File "/data2/longdan/project/CellViT-main/./preprocessing/patch_extraction/main_extraction.py", line 29, in <module>
    configuration, logger = configuration_parser.get_config()
  File "/data2/longdan/project/CellViT-main/preprocessing/patch_extraction/src/cli.py", line 590, in get_config
    yaml_config = PreProcessingYamlConfig(**yaml_config)
  File "/data2/longdan/anaconda3/envs/cellvit_env/lib/python3.9/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 28 validation errors for PreProcessingYamlConfig
wsi_extension
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
wsi_filelist
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
target_mpp
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
downsample
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
level
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
context_scales
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
check_resolution
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
annotation_paths
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
annotation_extension
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
incomplete_annotations
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
label_map_file
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
save_only_annotated_patches
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
exclude_classes
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
store_masks
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
generate_thumbnails
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
overlapping_labels
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
normalization_vector_json
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
adjust_brightness
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
tissue_annotation
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
tissue_annotation_intersection_ratio
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
masked_otsu
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
otsu_annotation
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
filter_patches
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
apply_prefilter
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
log_path
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
log_level
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
hardware_selection
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
wsi_properties
  Field required [type=missing, input_value={'wsi_paths': '/data2/lon...tersection_ratio': 0.05}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

**Comment by FabianHoerst** [comment]
Hi,

I think the pydantic version is not the one specified in the requirements.
