### ISSUE TITLE
IncompatibleKeys warning when replicating PanNuke experiment

### ISSUE THREAD

**Issue by schoonhovenrichard** [TIO-IKIM/CellViT#72]
**Describe the bug**
Whe running `cell_segmentation/run_cellvit.py` I get a large warning of many imcompatible keys trying to be loaded into the encoder. I set up the PanNuke dataset as described and using the ```cell_segmentation/datasets/prepare_pannuke.py``` script. Next, to replicate some experiments I use the config present in ```logs_paper/```:

```
python cell_segmentation/run_cellvit.py --config logs_paper/PanNuke/CellViTHV/SAM-B/Fold-1/config.yaml
```

In the config file I point to a `sam_vit_b.pth` file that I got from https://github.com/facebookresearch/segment-anything. The code ultimately runs but with a large warning (I will show only part of it):

```
Loading checkpoint: _IncompatibleKeys(missing_keys=['pos_embed', 'patch_embed.proj.weight', 'patch_embed.proj.bias', 
'blocks.0.norm1.weight', 'blocks.0.norm1.bias', 'blocks.0.attn.rel_pos_h', 'blocks.0.attn.rel_pos_w', 'blocks.0.attn.qkv.weight', 
'blocks.0.attn.qkv.bias', 'blocks.0.attn.proj.weight', 'blocks.0.attn.proj.bias', 'blocks.0.norm2.weight', 'blocks.0.norm2.bias', 
'blocks.0.mlp.lin1.weight', 'blocks.0.mlp.lin1.bias', 'blocks.0.mlp.lin2.weight', 'blocks.0.mlp.lin2.bias', 'blocks.1.norm1.weight', 
'blocks.1.norm1.bias', 'blocks.1.attn.rel_pos_h', 'blocks.1.attn.rel_pos_w', 'blocks.1.attn.qkv.weight', 'blocks.1.attn.qkv.bias', 
'blocks.1.attn.proj.weight', 'blocks.1.attn.proj.bias', 'blocks.1.norm2.weight', 'blocks.1.norm2.bias', 'blocks.1.mlp.lin1.weight', 
'blocks.1.mlp.lin1.bias', 'blocks.1.mlp.lin2.weight', 'blocks.1.mlp.lin2.bias', 'blocks.2.norm1.weight', 'blocks.2.norm1.bias', 
...
```

I did not make any modifications to CellViT so to reproduce requires running ```python cell_segmentation/run_cellvit.py --config logs_paper/PanNuke/CellViTHV/SAM-B/Fold-1/config.yaml``` with the dataset_path pointing to the processed PanNuke data, and in the ```config.yaml``` setting the pretrained_encoder to the ```sam_vit_b.pth``` path from the aforementioned link.

Is this normal/expected or is it somehow the wrong .pth file? In principle the model does appear to be training.

**Comment by FabianHoerst** [comment]
Hello,

the problem occurs that the SAM model from Facebook is "packed" within an entire structure including the decoder. We just used the encoder. You either need to match the keys and naming yourself, or you could use the cleaned encoders we provide here: https://drive.google.com/drive/u/1/folders/1UVwNHj9Y47j516SEUdtn1nlDau1kksDj

**Comment by schoonhovenrichard** [comment]
Thanks for the reply. I missed the difference between Meta's SAM models and your cleaned ones. After downloading yours the warning goes away. Thanks again!
