### ISSUE TITLE
Training on MoNuSeg

### ISSUE THREAD

**Issue by Hydroxide6** [TIO-IKIM/CellViT#80]
Currently, I am attempting to train a model using the MoNuSeg dataset. However, while looking through the code, I noticed that MoNuSeg is not supported yet, only PanNuke. I see that there is an existing MoNuSeg dataset preparation, so wondering why it is not supported.

Doing a little more digging, I found that the trainer utilizes data on the cell-type, which PanNuke provides and MoNuSeg does not. Is this the missing feature that prevents MoNuSeg from being used in training? Thanks!

**Comment by FabianHoerst** [comment]
Hello, 

As mentioned in our paper in Section 4.1, we did not train on the MoNuSeg dataset but performed inference on it. Therefore, we have provided the dataset preparation code but not the training code. However, you could implement a new trainer class to perform binary training on the MoNuSeg dataset. We hope this information is helpful to you! 

Best regards,  
Fabian
